create table candidates
(
    email      varchar(255) not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    resume     TEXT,
    id         bigint       not null,
    primary key (id)
);
create table employers
(
    email   varchar(255) not null,
    name    varchar(255) not null,
    website varchar(255),
    id      bigint       not null,
    primary key (id)
);
create table responses
(
    id            bigint generated by default as identity,
    cover_letter  TEXT,
    response_time timestamp not null,
    candidate_id  bigint    not null,
    vacancy_id    bigint    not null,
    primary key (id)
);
create table roles
(
    user_id bigint not null,
    roles   varchar(255)
);
create table users
(
    id       bigint not null,
    password varchar(255),
    username varchar(255),
    primary key (id)
);
create table vacancies
(
    id          bigint generated by default as identity,
    active      boolean      not null,
    description TEXT,
    title       varchar(255) not null,
    employer_id bigint       not null,
    primary key (id)
);
alter table if exists candidates
    drop constraint if exists UK_candidate_email;

alter table if exists candidates
    add constraint UK_candidate_email unique (email);
alter table if exists employers
    drop constraint if exists UK_employer_email;

alter table if exists employers
    add constraint UK_employer_email unique (email);
alter table if exists candidates
    add constraint FK_candidate_user foreign key (id) references users;
alter table if exists employers
    add constraint FK_employer_user foreign key (id) references users;
alter table if exists responses
    add constraint FK_response_candidate foreign key (candidate_id) references candidates;
alter table if exists responses
    add constraint FK_role_vacancy foreign key (vacancy_id) references vacancies;
alter table if exists roles
    add constraint FK_vacancy_user foreign key (user_id) references users;
alter table if exists vacancies
    add constraint FK_vacancy_employer foreign key (employer_id) references employers;
create sequence hibernate_sequence start 1 increment 1;

